# Site settings
title: TEDxYouth@Toronto
email: info@tedxyouthtoronto.ca
description: > # this means to ignore newlines until "baseurl:"
  tedxyouthtoronto
baseurl: ""
url: "http://tedxyouthtoronto.ca" # the base hostname & protocol for your site
twitter_username: TEDxYouthTO

# Build settings
markdown: kramdown
permalink: pretty

collections:
  team_members:
  speakers2014:
    output: true
  speakers2015:
    output: true
  speakers2016:
    output: true
  community:
    output: true
  sponsors:
