# Site settings
title: TEDxYouth@Toronto
email: info@tedxyouthtoronto.ca
description: > # this means to ignore newlines until "baseurl:"
  tedxyouthtoronto
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: TEDxYouthTO
github_username:  jekyll

# Build settings
markdown: kramdown

collections:
- team_members
- speakers2014
- speakers2015
- speakers2016